for i in *hopag1_*/*cif  
do              
python3 ../multidom_contacts.py -c $i -d 'VIETDKWSQLSGAKGSNPGGLFQAPDGVKWYVKTNPSTNRLRNEVLASKLYRAAGIDVPDIKMASRQGKPALISKLIGGNHKDIKTIEGSGQLRSGFAVDAWLANWDVIGQTGDNIIFNDRNKPVRIDLGGSLLFRAQGGHKGNQFGNTPMELVTMLSRKENTSSHAFRKIERNDIRMGIAAIERIPDDRIKALCAEHGPGNYSERIELGKRLISRKHWLVNMKQTLPHIHRQK' -o $(basename $i)_Kinase
done
